use PetAPuppyLukasFuller
delete from tblUsers

insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Bob', 'test123', '2018-10-01', 0, null, '' , 'my stuff no work :<', 'high')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Joe', 'test123', '2018-10-01', 0, null, '' , 'my stuff no work :(', 'high')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Billy', 'test123', '2018-10-01', 0, null, '' , 'my stuff no work D:', 'high')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Jane', 'test123', '2018-10-01', 0, null, '' , 'my stuff no work :o', 'high')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Gavin', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Jayne', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :<', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Pearl', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :(', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('James', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work D:', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Tyler', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :o', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Zach', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Alec', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :<', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Oliver', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work :<', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Harry', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work :(', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Jack', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work D:', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('George', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work :o', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Logan', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Finley', 'test123', '2018-12-10', 0, null, '' , 'my stuff no work :<', 'low')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Max', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :(', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Willy', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work D:', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Jake', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :o', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Xqc', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Hugo', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :<', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Richard', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :o', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Aron', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work', 'medium')
insert into tblUsers (UserName,Password, CreateDate,  resolvedTicket, modifiedDate, modifiedBy, ticketDescription, priority)
values('Aiden', 'test123', '2018-12-04', 0, null, '' , 'my stuff no work :<', 'medium')